version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    environment:
      - N8N_BASIC_AUTH_ACTIVE=${N8N_BASIC_AUTH_ACTIVE:-true}
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER:-admin}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - N8N_HOST=${N8N_HOST:-localhost}
      - N8N_PORT=${N8N_PORT:-5678}
      - N8N_PROTOCOL=${N8N_PROTOCOL:-http}
      - WEBHOOK_URL=${WEBHOOK_URL:-http://localhost:5678}
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE:-UTC}
      # Database settings (optional - uses SQLite by default)
      - DB_TYPE=${DB_TYPE:-sqlite}
      - DB_SQLITE_DATABASE=${DB_SQLITE_DATABASE:-/home/node/.n8n/database.sqlite}
      # PostgreSQL settings (uncomment if using PostgreSQL)
      # - DB_TYPE=postgresdb
      # - DB_POSTGRESDB_HOST=${DB_POSTGRESDB_HOST:-postgres}
      # - DB_POSTGRESDB_PORT=${DB_POSTGRESDB_PORT:-5432}
      # - DB_POSTGRESDB_DATABASE=${DB_POSTGRESDB_DATABASE:-n8n}
      # - DB_POSTGRESDB_USER=${DB_POSTGRESDB_USER:-n8n}
      # - DB_POSTGRESDB_PASSWORD=${DB_POSTGRESDB_PASSWORD}
    ports:
      - "${N8N_PORT:-5678}:5678"
    volumes:
      - n8n_data:/home/node/.n8n
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:5678/healthz || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - n8n
    labels:
      # Nginx proxy labels (if using nginx-proxy module)
      - "VIRTUAL_HOST=${N8N_HOST:-localhost}"
      - "VIRTUAL_PORT=5678"
      - "LETSENCRYPT_HOST=${N8N_HOST:-localhost}"
      - "LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}"

volumes:
  n8n_data:

networks:
  n8n:
    driver: bridge
  # Uncomment to connect to nginx-proxy
  # proxy:
  #   external: true