version: '3.8'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:1.4
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx_certs:/etc/nginx/certs
      - nginx_html:/usr/share/nginx/html
      - nginx_dhparam:/etc/nginx/dhparam
    environment:
      - DEFAULT_HOST=${DEFAULT_HOST:-localhost}
      - TRUST_DOWNSTREAM_PROXY=${TRUST_DOWNSTREAM_PROXY:-false}
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    restart: unless-stopped
    networks:
      - proxy

  letsencrypt:
    image: nginxproxy/acme-companion:2.2
    container_name: nginx-proxy-acme
    depends_on:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx_certs:/etc/nginx/certs
      - nginx_html:/usr/share/nginx/html
      - nginx_dhparam:/etc/nginx/dhparam
      - acme:/etc/acme.sh
    environment:
      - DEFAULT_EMAIL=${LETSENCRYPT_EMAIL}
      - NGINX_PROXY_CONTAINER=nginx-proxy
    restart: unless-stopped
    networks:
      - proxy

volumes:
  nginx_certs:
  nginx_html:
  nginx_dhparam:
  acme:

networks:
  proxy:
    external: true